from settings import *

def test_array_with_dep_3_5(ims_test):
    """Test for IMS ARRAY WITH dependency between 3 and 5"""
    create_task(ims_test)
    ims_test.ims_db.cursor.execute("DELETE FROM \"DEVPCB\".\"STRUCT2\"")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_1COL_1_COL1)"
        "VALUES ('ROOT000002', 'KEY1', 1, 99, 08, 26, 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1)"
        "VALUES ('ROOT000002', 'KEY2', 2, 99, 08, 26, 01, 12, 27, 'AAAAA', 'BBBBB')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1)"
        "VALUES ('ROOT000002', 'KEY3', 3, 99, 08, 26, 01, 12, 27, 22, 10, 12, 'AAAAA', 'BBBBB', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD , DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD,DATE_ARRAY_4_DATE_YY, DATE_ARRAY_4_DATE_MM, DATE_ARRAY_4_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1, DATE_ARRAY_1COL_4_COL1)"
        "VALUES ('ROOT000002', 'KEY4', 4, 99, 08, 26, 99, 08, 26, 99, 08, 26, 99, 08, 26, 'AAAAA', 'AAAAA','AAAAA', 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD,DATE_ARRAY_4_DATE_YY, DATE_ARRAY_4_DATE_MM, DATE_ARRAY_4_DATE_DD, DATE_ARRAY_5_DATE_YY, DATE_ARRAY_5_DATE_MM, DATE_ARRAY_5_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1, DATE_ARRAY_1COL_4_COL1, DATE_ARRAY_1COL_5_COL1)"
        "VALUES ('ROOT000002', 'KEY5', 5, 99, 08, 26, 01, 12, 27, 99, 08, 26, 01, 12, 27, 99, 08, 26, 'AAAAA', 'BBBBB', 'AAAAA', 'BBBBB', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD,DATE_ARRAY_4_DATE_YY, DATE_ARRAY_4_DATE_MM, DATE_ARRAY_4_DATE_DD, DATE_ARRAY_5_DATE_YY, DATE_ARRAY_5_DATE_MM, DATE_ARRAY_5_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1, DATE_ARRAY_1COL_4_COL1, DATE_ARRAY_1COL_5_COL1)"
        "VALUES ('ROOT000002', 'KEY6', 6, 99, 08, 26, 01, 12, 27, 22, 10, 12, 99, 08, 26, 01, 12, 27, 'AAAAA', 'BBBBB', 'CCCCC', 'AAAAA', 'BBBBB')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_1COL_1_COL1)"
        "VALUES ('ROOT000002', 'KEY7', 0, 99, 08, 26, 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY)" 
        "VALUES ('ROOT000002', 'KEY8')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM)" 
        "VALUES ('ROOT000002', 'KEY9', 0)")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1)"
        "VALUES ('ROOT000002', 'KEY10', 99, 08, 26, 01, 12, 27, 22, 10, 12, 'AAAAA', 'BBBBB', 'CCCCC')")
    ims_test.ims_db.connection.commit()
    ims_test.designer_page.run_new_task()
    ims_test.monitor_page.wait_for_fl('2')
    ims_test.monitor_page.cdc_tab()
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_1COL_1_COL1)"
        "VALUES ('ROOT000002', 'KEY11', 1, 99, 08, 26, 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1)"
        "VALUES ('ROOT000002', 'KEY12', 2, 99, 08, 26, 01, 12, 27, 'AAAAA', 'BBBBB')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1)"
        "VALUES ('ROOT000002', 'KEY13', 3, 99, 08, 26, 01, 12, 27, 22, 10, 12, 'AAAAA', 'BBBBB', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD , DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD,DATE_ARRAY_4_DATE_YY, DATE_ARRAY_4_DATE_MM, DATE_ARRAY_4_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1, DATE_ARRAY_1COL_4_COL1)"
        "VALUES ('ROOT000002', 'KEY14', 4, 99, 08, 26, 99, 08, 26, 99, 08, 26, 99, 08, 26, 'AAAAA', 'AAAAA','AAAAA', 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD,DATE_ARRAY_4_DATE_YY, DATE_ARRAY_4_DATE_MM, DATE_ARRAY_4_DATE_DD, DATE_ARRAY_5_DATE_YY, DATE_ARRAY_5_DATE_MM, DATE_ARRAY_5_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1, DATE_ARRAY_1COL_4_COL1, DATE_ARRAY_1COL_5_COL1)"
        "VALUES ('ROOT000002', 'KEY15', 5, 99, 08, 26, 01, 12, 27, 99, 08, 26, 01, 12, 27, 99, 08, 26, 'AAAAA', 'BBBBB', 'AAAAA', 'BBBBB', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD,DATE_ARRAY_4_DATE_YY, DATE_ARRAY_4_DATE_MM, DATE_ARRAY_4_DATE_DD, DATE_ARRAY_5_DATE_YY, DATE_ARRAY_5_DATE_MM, DATE_ARRAY_5_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1, DATE_ARRAY_1COL_4_COL1, DATE_ARRAY_1COL_5_COL1)"
        "VALUES ('ROOT000002', 'KEY16', 6, 99, 08, 26, 01, 12, 27, 22, 10, 12, 99, 08, 26, 01, 12, 27, 'AAAAA', 'BBBBB', 'CCCCC', 'AAAAA', 'BBBBB')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_1COL_1_COL1)"
        "VALUES ('ROOT000002', 'KEY17', 0, 99, 08, 26, 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY)" 
        "VALUES ('ROOT000002', 'KEY18')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATES_NUM)" 
        "VALUES ('ROOT000002', 'KEY19', 0)")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT2\" (ROOT_ROOTID, SKEY, DATE_ARRAY_1_DATE_YY, DATE_ARRAY_1_DATE_MM, DATE_ARRAY_1_DATE_DD, DATE_ARRAY_2_DATE_YY, DATE_ARRAY_2_DATE_MM, DATE_ARRAY_2_DATE_DD, DATE_ARRAY_3_DATE_YY, DATE_ARRAY_3_DATE_MM, DATE_ARRAY_3_DATE_DD, DATE_ARRAY_1COL_1_COL1, DATE_ARRAY_1COL_2_COL1, DATE_ARRAY_1COL_3_COL1)"
        "VALUES ('ROOT000002', 'KEY20', 99, 08, 26, 01, 12, 27, 22, 10, 12, 'AAAAA', 'BBBBB', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"UPDATE \"DEVPCB\".\"STRUCT2\" SET DATES_NUM = 3, DATE_ARRAY_1_DATE_YY = 11, DATE_ARRAY_1_DATE_MM = 11, DATE_ARRAY_1_DATE_DD = 11, DATE_ARRAY_1COL_1_COL1 = 'UPDAT', DATE_ARRAY_2_DATE_YY = 11, DATE_ARRAY_2_DATE_MM = 11, DATE_ARRAY_2_DATE_DD = 11, DATE_ARRAY_1COL_2_COL1 = 'UPDAT', DATE_ARRAY_3_DATE_YY = 11, DATE_ARRAY_3_DATE_MM = 11, DATE_ARRAY_3_DATE_DD = 11, DATE_ARRAY_1COL_3_COL1 = 'UPDAT' WHERE SKEY = 'KEY1'")
    ims_test.ims_db.cursor.execute(
        f"UPDATE \"DEVPCB\".\"STRUCT2\" SET DATES_NUM = 3, DATE_ARRAY_1_DATE_YY = 88, DATE_ARRAY_1_DATE_MM = 88, DATE_ARRAY_1_DATE_DD = 88, DATE_ARRAY_1COL_1_COL1 = 'UPDAT', DATE_ARRAY_2_DATE_YY = 88, DATE_ARRAY_2_DATE_MM = 88, DATE_ARRAY_2_DATE_DD = 88, DATE_ARRAY_1COL_2_COL1 = 'UPDAT', DATE_ARRAY_3_DATE_YY = 88, DATE_ARRAY_3_DATE_MM = 88, DATE_ARRAY_3_DATE_DD = 88, DATE_ARRAY_1COL_3_COL1 = 'UPDAT' WHERE SKEY = 'KEY8'")
    ims_test.ims_db.cursor.execute(
        f"UPDATE \"DEVPCB\".\"STRUCT2\" SET DATES_NUM = 3, DATE_ARRAY_1_DATE_YY = 55, DATE_ARRAY_1_DATE_MM = 55, DATE_ARRAY_1_DATE_DD = 55, DATE_ARRAY_1COL_1_COL1 = 'UPDAT', DATE_ARRAY_2_DATE_YY = 55, DATE_ARRAY_2_DATE_MM = 55, DATE_ARRAY_2_DATE_DD = 55, DATE_ARRAY_1COL_2_COL1 = 'UPDAT', DATE_ARRAY_3_DATE_YY = 55, DATE_ARRAY_3_DATE_MM = 55, DATE_ARRAY_3_DATE_DD = 55, DATE_ARRAY_1COL_3_COL1 = 'UPDAT' WHERE SKEY = 'KEY5'")
    ims_test.ims_db.cursor.execute(f"DELETE FROM \"DEVPCB\".\"STRUCT2\" WHERE SKEY = 'KEY10'")
    ims_test.ims_db.cursor.execute(f"DELETE FROM \"DEVPCB\".\"STRUCT2\" WHERE SKEY = 'KEY3'")
    ims_test.ims_db.connection.commit()
    ims_test.ims_db.sync_command()
    ims_test.monitor_page.insert_check('18', '10')
    ims_test.monitor_page.update_check('3', '3')
    ims_test.monitor_page.delete_check('5', '2')
    ims_test.monitor_page.wait_for_cdc()
    ims_test.monitor_page.stop_task()
    ims_test.monitor_page.stop_task_wait()
    ims_test.replicate_actions.navigate_to_main_page('tasks')
    move_file_to_target_dir(ims_test.config.source_tasklog_path(), ims_test.task_logs_dir,f"reptask_{ims_test.task_name}.log", ims_test.config)
    ims_test.target_db.export_schema_data_to_csv(ims_test.target_schema,
                                                 ims_test.good_files_dir + f"\\IMS_2_{ims_test.target_db.config['endpoint']}_ARRAY_DEP_3_5.csv")
    compare_files(ims_test.good_files_dir + f"\\IMS_2_{ims_test.target_db.config['endpoint']}_ARRAY_DEP_3_5.good",
                  ims_test.good_files_dir + f"\\IMS_2_{ims_test.target_db.config['endpoint']}_ARRAY_DEP_3_5.csv")