from replicate_pages.common_functions import CommonFunctions
from replicate_pages.tasks_view_page import TasksPage
from replicate_pages.new_task_page import NewTaskPage
from replicate_pages.manage_endpoints_page import ManageEndpoints
from replicate_pages.task_settings_page import TaskSettings
from replicate_pages.table_selection_page import TableSelection
from replicate_pages.designer_page import DesignerPage
from replicate_pages.monitor_page import MonitorPage
