from settings import *

def test_array_in_array(ims_test):
    """Test for IMS ARRAY inside an ARRAY"""
    create_task(ims_test)

    ims_test.ims_db.cursor.execute("DELETE FROM \"DEVPCB\".\"STRUCT3\"")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY1', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY2', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY3', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY4', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY5', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY6', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE)"
        "VALUES ('ROOT000003', 'KEY7', 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1)"
        "VALUES ('ROOT000003', 'KEY8', 'BBBBB')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2)"
        "VALUES ('ROOT000003', 'KEY9', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3)"
        "VALUES ('ROOT000003', 'KEY10', 'DDDDD')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4)"
        "VALUES ('ROOT000003', 'KEY11', 'EEEEE')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY12', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY) VALUES ('ROOT000003', 'KEY13')")
    ims_test.ims_db.connection.commit()

    ims_test.designer_page.run_new_task()
    ims_test.monitor_page.wait_for_fl('6')
    ims_test.monitor_page.cdc_tab()

    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY14', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY15', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY16', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY17', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY18', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY19', 'AAAAA', 'BBBBB', 'CCCCC', 'DDDDD', 'EEEEE', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_CHAR_COL_BASE)"
        "VALUES ('ROOT000003', 'KEY20', 'AAAAA')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1)"
        "VALUES ('ROOT000003', 'KEY21', 'BBBBB')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2)"
        "VALUES ('ROOT000003', 'KEY22', 'CCCCC')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3)"
        "VALUES ('ROOT000003', 'KEY23', 'DDDDD')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4)"
        "VALUES ('ROOT000003', 'KEY24', 'EEEEE')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY, ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5)"
        "VALUES ('ROOT000003', 'KEY25', 'FFFFF')")
    ims_test.ims_db.cursor.execute(
        f"INSERT INTO \"DEVPCB\".\"STRUCT3\" (ROOT_ROOTID, SKEY) VALUES ('ROOT000003', 'KEY26')")

    ims_test.ims_db.cursor.execute(
        f"UPDATE \"DEVPCB\".\"STRUCT3\" SET ARRAY_BASE_1_CHAR_COL_BASE = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5 = 'UPDAT' WHERE SKEY = 'KEY2'")
    ims_test.ims_db.cursor.execute(
        f"UPDATE \"DEVPCB\".\"STRUCT3\" SET ARRAY_BASE_1_CHAR_COL_BASE = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_CHAR_COL_1 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_CHAR_COL_2 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_CHAR_COL_3 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_CHAR_COL_4 = 'UPDAT', ARRAY_BASE_1_ARRAY_1_1_ARRAY_2_1_ARRAY_3_1_ARRAY_4_1_ARRAY_5_1_CHAR_COL_5 = 'UPDAT' WHERE SKEY = 'KEY3'")

    ims_test.ims_db.cursor.execute(f"DELETE FROM \"DEVPCB\".\"STRUCT3\" WHERE SKEY = 'KEY1'")
    ims_test.ims_db.cursor.execute(f"DELETE FROM \"DEVPCB\".\"STRUCT3\" WHERE SKEY = 'KEY7'")
    ims_test.ims_db.connection.commit()

    ims_test.ims_db.sync_command()

    ims_test.monitor_page.wait_for_cdc()
    ims_test.monitor_page.insert_check('11', '10', '9', '8', '12', '13')
    ims_test.monitor_page.update_check('2', '2', '2', '2', '2', '0')
    ims_test.monitor_page.delete_check('1', '1', '1', '1', '2', '2')
    ims_test.monitor_page.stop_task()
    ims_test.monitor_page.stop_task_wait()

    ims_test.replicate_actions.navigate_to_main_page('tasks')
    move_file_to_target_dir(ims_test.config.replicate_logs_path(), ims_test.task_logs_dir,
                            f"reptask_{ims_test.task_name}.log", ims_test.config, ims_test.replicate_actions, ims_test.task_name)
    ims_test.target_db.export_schema_data_to_csv(ims_test.target_schema,
                                                 ims_test.good_files_dir + f"\\IMS_2_{ims_test.target_db.config['endpoint']}_ARRAY_IN_ARRAY.csv")
    compare_files(ims_test.good_files_dir + f"\\IMS_2_{ims_test.target_db.config['endpoint']}_ARRAY_IN_ARRAY.good",
                  ims_test.good_files_dir + f"\\IMS_2_{ims_test.target_db.config['endpoint']}_ARRAY_IN_ARRAY.csv")